"""add labs and user_lab_progress tables

Revision ID: 08c341c4dde8
Revises: af246f9e2e24
Create Date: 2026-07-17 22:25:51.692217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c341c4dde8'
down_revision: Union[str, None] = 'af246f9e2e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='labdifficulty', native_enum=False, length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_category'), 'labs', ['category'], unique=False)
    op.create_index(op.f('ix_labs_slug'), 'labs', ['slug'], unique=True)
    op.create_table('user_lab_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lab_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='progressstatus', native_enum=False, length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lab_id', name='uq_user_lab_progress')
    )
    op.create_index(op.f('ix_user_lab_progress_lab_id'), 'user_lab_progress', ['lab_id'], unique=False)
    op.create_index(op.f('ix_user_lab_progress_user_id'), 'user_lab_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_lab_progress_user_id'), table_name='user_lab_progress')
    op.drop_index(op.f('ix_user_lab_progress_lab_id'), table_name='user_lab_progress')
    op.drop_table('user_lab_progress')
    op.drop_index(op.f('ix_labs_slug'), table_name='labs')
    op.drop_index(op.f('ix_labs_category'), table_name='labs')
    op.drop_table('labs')
    # ### end Alembic commands ###
