"""add challenges and user_challenge_progress tables

Revision ID: e6e4c68ab71c
Revises: 08c341c4dde8
Create Date: 2026-07-18 20:04:08.720256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6e4c68ab71c'
down_revision: Union[str, None] = '08c341c4dde8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lab_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('challenge_type', sa.Enum('FLAG', 'QUIZ', 'TEXT', name='challengetype', native_enum=False, length=10), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('flag_hash', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_lab_id'), 'challenges', ['lab_id'], unique=False)
    op.create_table('user_challenge_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_user_challenge_progress')
    )
    op.create_index(op.f('ix_user_challenge_progress_challenge_id'), 'user_challenge_progress', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_user_challenge_progress_user_id'), 'user_challenge_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_challenge_progress_user_id'), table_name='user_challenge_progress')
    op.drop_index(op.f('ix_user_challenge_progress_challenge_id'), table_name='user_challenge_progress')
    op.drop_table('user_challenge_progress')
    op.drop_index(op.f('ix_challenges_lab_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
